### ISSUE TITLE
Unable to resolve file path?

### ISSUE THREAD

**Issue by rafaelrinaldi** [dot-build/rollup-plugin-includepaths#2]
My current folder scructure:

```
.
├── package.json
├── rollup.config.js
├── public
├── source
│   ├── scripts
│   │   └── index.js
│   │   └── utils
│   │       └── select.js
```

My `rollup.config.js`:

```js
import resolve from 'rollup-plugin-node-resolve';
import cjs from 'rollup-plugin-commonjs';
import es6 from 'rollup-plugin-babel';
import uglify from 'rollup-plugin-uglify';
import paths from 'rollup-plugin-includepaths';

const plugins = [
  paths({
    include: {
      select: 'source/scripts/utils/select.js'
    }
  }),
  resolve({
    main: true,
    browser: true
  }),
  cjs(),
  es6()
];

export default {
  entry: 'source/scripts/index.js',
  dest: 'public/bundle.js',
  format: 'iife',
  plugins
};
```

When I try to reference the alias for my module:

```js
/* some-file.js */
import select from 'select';
```

I get this error:

```
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at RollupIncludePaths.searchProjectModule (/Users/rafaelrinaldi/work/project/node_modules/rollup-plugin-includepaths/src/plugin.es5.js:191:45)
    at RollupIncludePaths.searchModule (/Users/rafaelrinaldi/work/project/node_modules/rollup-plugin-includepaths/src/plugin.es5.js:164:73)
    at RollupIncludePaths.resolveId (/Users/rafaelrinaldi/work/project/node_modules/rollup-plugin-includepaths/src/plugin.es5.js:89:55)
    at resolveId (/Users/rafaelrinaldi/work/project/node_modules/rollup-plugin-includepaths/src/plugin.es5.js:301:29)
    at /Users/rafaelrinaldi/work/project/node_modules/rollup/www/ROLLUP/rollup/src/utils/first.js:10:31
    at tryCatch (/Users/rafaelrinaldi/work/project/node_modules/rollup/www/ROLLUP/rollup/node_modules/es6-promise/lib/es6-promise/-internal.js:185:12)
    at invokeCallback (/Users/rafaelrinaldi/work/project/node_modules/rollup/www/ROLLUP/rollup/node_modules/es6-promise/lib/es6-promise/-internal.js:197:13)
    at publish (/Users/rafaelrinaldi/work/project/node_modules/rollup/www/ROLLUP/rollup/node_modules/es6-promise/lib/es6-promise/-internal.js:168:7)
    at flush (/Users/rafaelrinaldi/work/project/node_modules/rollup/www/ROLLUP/rollup/node_modules/es6-promise/lib/es6-promise/asap.js:87:5)
    at _combinedTickCallback (node.js:370:9)
```

Environment settings:

```
~/work/project master*
❯ npm -v
3.8.2

~/work/project master*
❯ node -v
v5.8.0

~/work/project master*
❯ cat package.json | ag includepaths
    "rollup-plugin-includepaths": "^0.1.1",
```

From the stack trace it seems to be Rollup not finding the path for `select.js` which therefore seems to be a bug on the path resolution of this plugin.

Am I doing something wrong?

Thanks.

**Comment by darlanalves** [comment]
Hi buddy! Sorry the late reply. Been offline this week.

There's one thing you are missing: the include paths for this plugin to work.
The point of this plugin is to iterate over some directories and try to get a match for path + included module, so you don't have to "hardcode" the source path for everything.

This is also my fault. I should emit an error if include paths are not defined in the setup. I'll fix that.

As a sidenote, be aware that the "include" option completely skips the name resolution. The file path defined there is used instead, additionally including a file extension if not present (`.js`).
